return {
	[1] = {
		reward = 100,
		groups = {
			{ enemy = "Bung Bung",            count = 5, interval = 2.0, hp = 80,  speed = 12 },
		},
	},
	[2] = {
		reward = 150,
		groups = {
			{ enemy = "Bung Bung",            count = 8, interval = 1.5, hp = 100, speed = 14 },
			{ enemy = "Jota Ele Dim Dim Dim", count = 3, interval = 2.5, hp = 60,  speed = 22 },
		},
	},
	[3] = {
		reward = 300,
		groups = {
			{ enemy = "Bung Bung",              count = 10, interval = 1.2, hp = 130, speed = 14 },
			{ enemy = "Jota Ele Dim Dim Dim",   count = 5,  interval = 2.0, hp = 80,  speed = 22 },
			{ enemy = "Bailarina Sapatina Boss", count = 1, interval = 0,   hp = 800, speed = 7  },
		},
	},
}
